openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact database
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contact database
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:8080
  - url: https://staging.yourdomain.com/v1
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/patch.yaml
  # /auth:
  # post:
  #   $ref:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
